name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - run: deno --version

      - name: Run unit tests
        run: deno test --allow-net
