name: CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: [1.x]
    name: test ${{ matrix.deno }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno --version
      - run: deno test --allow-net
